# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('printed', models.BooleanField(default=False)),
                ('rtype', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='normal', max_length=16)),
            ],
            options={
                'ordering': ('issued',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rix', models.PositiveSmallIntegerField()),
                ('ritype', models.CharField(choices=[('normal1', 'Basic'), ('normal2', 'Intermediate'), ('normal3', 'Advanced')], default='normal1', max_length=16)),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Shopping')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItemNormal1',
            fields=[
                ('shoppingitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.ShoppingItemBase')),
                ('name', models.CharField(default='meno', max_length=128)),
                ('color', models.CharField(default='cierna', max_length=128)),
            ],
            bases=('testapp.shoppingitembase',),
        ),
        migrations.CreateModel(
            name='ShoppingItemNormal2',
            fields=[
                ('shoppingitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.ShoppingItemBase')),
                ('title', models.CharField(default='nazov', max_length=128)),
                ('text', models.CharField(default='popis', max_length=128)),
            ],
            bases=('testapp.shoppingitembase',),
        ),
        migrations.AddField(
            model_name='shoppingitembase',
            name='shopping_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='testapp.ShoppingItem'),
        ),
    ]
