# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('printed', models.BooleanField(default=False)),
                ('rtype', models.CharField(choices=[('type1', 'Basic'), ('type2', 'Intermediate'), ('type3', 'Advanced')], default='normal', max_length=16)),
            ],
            options={
                'ordering': ('issued',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rix', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('unit_si', models.CharField(max_length=16)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('value', models.DecimalField(decimal_places=10, max_digits=24)),
                ('vat', models.FloatField()),
                ('vat_class', models.CharField(max_length=16)),
                ('currency', models.CharField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='ritype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.ShoppingItemType'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='shopping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Shopping'),
        ),
    ]
