# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitemtype',
            name='currency',
            field=models.CharField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], max_length=30),
        ),
    ]
