# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitemnormal1',
            name='color',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='shoppingitemnormal1',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
