# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_shoppingitemtype_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItemNormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('unit_si', models.CharField(max_length=16)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('value', models.DecimalField(decimal_places=10, max_digits=24)),
                ('vat', models.FloatField()),
                ('vat_class', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='ritype',
            field=models.CharField(choices=[(1, 'normal'), (2, 'best')], default='normal', max_length=16),
        ),
        migrations.DeleteModel(
            name='ShoppingItemType',
        ),
        migrations.AddField(
            model_name='shoppingitemnormal',
            name='shopping_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.ShoppingItem'),
        ),
    ]
