# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20171108_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='ritype',
            field=models.CharField(choices=[('normal', 'normal'), ('test', 'test')], default='normal', max_length=16),
        ),
    ]
