# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20171108_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopingItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.ShoppingItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingitemnormal',
            name='shopping_item',
        ),
        migrations.DeleteModel(
            name='ShoppingItemNormal',
        ),
    ]
