# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20171108_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItemNormal',
            fields=[
                ('shopingitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.ShopingItemBase')),
                ('name', models.CharField(default='test', max_length=128)),
                ('color', models.CharField(default='blue', max_length=128)),
            ],
            bases=('testapp.shopingitembase',),
        ),
        migrations.CreateModel(
            name='ShoppingItemNormal2',
            fields=[
                ('shopingitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.ShopingItemBase')),
                ('title', models.CharField(default='title', max_length=128)),
                ('text', models.CharField(default='text', max_length=128)),
            ],
            bases=('testapp.shopingitembase',),
        ),
    ]
