# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20171108_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingitembase',
            name='shopping_type',
            field=models.CharField(choices=[('ShoppingItemNormal', 'ShoppingItemNormal'), ('ShoppingItemNormal2', 'ShoppingItemNormal2')], default='ShoppingItemNormal', max_length=255),
        ),
    ]
