# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_shopingitembase_shopping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingitembase',
            name='shopping_type',
            field=models.CharField(choices=[('shoppingitemnormal', 'ShoppingItemNormal'), ('shoppingitemnormal2', 'ShoppingItemNormal2')], default='ShoppingItemNormal', max_length=255),
        ),
    ]
