# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20171108_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingitembase',
            name='shopping_type',
            field=models.CharField(choices=[('shoppingitemnormal', 'shoppingitemnormal'), ('shoppingitemnormal2', 'shoppingitemnormal2')], default='ShoppingItemNormal', max_length=255),
        ),
    ]
