# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20171108_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingitembase',
            name='shopping_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='testapp.ShoppingItem'),
        ),
    ]
